# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170612_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
