# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='followup',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_per_lecture',
            field=models.PositiveIntegerField(),
        ),
    ]
