# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170613_1543'),
        ('AskARi', '0005_auto_20170615_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted',
            field=models.ManyToManyField(related_name='downvoted', to='login.ARiProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted',
            field=models.ManyToManyField(related_name='upvoted', to='login.ARiProfile'),
        ),
    ]
