# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0006_auto_20170616_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvoted',
            field=models.ManyToManyField(to='login.ARiProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='login.ARiProfile'),
        ),
    ]
