# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0007_auto_20170616_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvoted',
            field=models.ManyToManyField(related_name='downvoted_set', to='login.ARiProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_set', to='login.ARiProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvoted',
            field=models.ManyToManyField(related_name='upvoted_set', to='login.ARiProfile'),
        ),
    ]
