# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0008_auto_20170616_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_per_question',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_per_lecture',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
