# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 12:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('AskARi', '0013_question_last_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndCurrentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_comment_ids', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='downvoted',
            new_name='downvoters',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='upvoted',
            new_name='upvoters',
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='AskARi.Comment'),
        ),
    ]
